---
identifier: devportal-api
blueprint: service
description: developer portal api service
qos: critical
tier: 1
product_manager: kagamicat
owning_team: github/feature-delivery
exec_sponsor: smeirsha
name: devportal-api
repository: https://github.com/github/devportal-api
links:
- description: Playbook for the Developer Portal API
  kind: playbook
  name: Developer Portal API Playbook
  source: https://github.com/github/devportal-api/blob/763d600f8e368c0298c391e8e94466280be32ffe/ownership.yaml
    via ownership_load
  url: https://ops.githubapp.com/docs/playbooks/devportal-api.md
- description: Service-level documentation for the Developer Portal API
  kind: docs
  name: Developer Portal API Service Documentation
  source: https://github.com/github/devportal-api/blob/763d600f8e368c0298c391e8e94466280be32ffe/ownership.yaml
    via ownership_load
  url: https://ops.githubapp.com/docs/services/devportal-api.md
- description: request tracing
  kind: dashboard
  name: Lightstep
  source: https://github.com/github/devportal-api/blob/763d600f8e368c0298c391e8e94466280be32ffe/ownership.yaml
    via ownership_load
  url: https://app.lightstep.com/github-prod/service-directory/devportal-api/operations
- description: A dashboard with metrics for Developer Portal and other Moda services
  kind: dashboard
  name: Moda and Developer Portal Dashboard
  source: https://github.com/github/devportal-api/blob/763d600f8e368c0298c391e8e94466280be32ffe/ownership.yaml
    via ownership_load
  url: https://app.datadoghq.com/dashboard/mce-d98-324/mads-moda-and-devportal-services
- description: Service status
  kind: tool
  name: Moda Home Page
  source: cat-graphql via GraphQL
  url: https://devportal.githubapp.com/devportal/apps/devportal-api?tab=deployenvs
- description: unhandled exceptions
  kind: dashboard
  name: Sentry
  source: https://github.com/github/devportal-api/blob/763d600f8e368c0298c391e8e94466280be32ffe/ownership.yaml
    via ownership_load
  url: https://github.sentry.io/issues/?project=4504327115177984
support_escalations:
- level: sev2
  tta: 1 business days
  github_issues: https://github.com/github/devportal-api/issues
  slack_alert: moda-alerts
- level: sev3
  tta: 1 week
  github_issues: https://github.com/github/devportal-api/issues
- level: sev1
  tta: 10 min
  slack_alert: moda-alerts
  pagerduty: POA91SN
- level: Team Slack
  slack: feature-delivery-team
owning_entitlement_teams:
- feature-delivery
